### ISSUE TITLE
[fix] Limit the height of SVG wave(s)

### ISSUE THREAD

**Issue by rahuldahal** [askbuddie/askbuddie-bot-docs#13]
**The problem**
Currently, the "wave" SVGs do not have a max-height. Therefore, it grows taller than the design expects.

**Describe the solution you'd like**
On [this](https://github.com/askbuddie/askbuddie-bot-docs/blob/04e8085d8d7d282898b63e40d94ed4b8ffb039e0/components/Landing/Hero.js#L29) and  [this](https://github.com/askbuddie/askbuddie-bot-docs/blob/04e8085d8d7d282898b63e40d94ed4b8ffb039e0/components/Landing/About.js#L24) line(s), add `max-h-screen-sm` in the `className` prop.

**Comment by rahuldahal** [comment]
Remember to send the PR to the `development` branch, not `master`

**Comment by ap211unitech** [comment]
I would like to solve this issue. Please allow me to do.

**Comment by rahuldahal** [comment]
@ap211unitech  okay, you can.
Don't change anything else. Just follow the described instructions.
