### ISSUE TITLE
Clean up the footer

### ISSUE THREAD

**Issue by rahuldahal-zz** [askbuddie/askbuddie-bot-docs#23]
**The problem**
The [footer](https://github.com/askbuddie/askbuddie-bot-docs/blob/development/components/Footer/index.js) currently has these rather unnecessary links on the right side.
![image](https://user-images.githubusercontent.com/44515005/132087462-33b9d279-25de-4540-b005-a9f50ea678cd.png)

**The Solution**
Remove all those links and make sure the footer only has this section on it.
![image](https://user-images.githubusercontent.com/44515005/132087519-d418bd4b-9cad-43d6-9281-e453be8bccae.png)

**Comment by ARJITMALIK** [comment]
Hey @rahuldahal, may I take this issue.
