### ISSUE TITLE
only show pseudo elements on wider screens(>768px)

### ISSUE THREAD

**Issue by rahuldahal-zz** [askbuddie/askbuddie-bot-docs#25]
**Describe the solution you'd like**
On the community section's CSS, wrap [line 93](https://github.com/askbuddie/askbuddie-bot-docs/blob/f120fe043d1b1fcd9dfacaa874b66f1d32ca025a/styles/custom.css#L93) to [line 101](https://github.com/askbuddie/askbuddie-bot-docs/blob/f120fe043d1b1fcd9dfacaa874b66f1d32ca025a/styles/custom.css#L101) inside a `@media (min-width: 768px){}` block.

Do the same for [line 109](https://github.com/askbuddie/askbuddie-bot-docs/blob/f120fe043d1b1fcd9dfacaa874b66f1d32ca025a/styles/custom.css#L109) to [line 116](https://github.com/askbuddie/askbuddie-bot-docs/blob/f120fe043d1b1fcd9dfacaa874b66f1d32ca025a/styles/custom.css#L116)

**Additional context**
Make sure,
- that those pseudo-elements are only visible when the viewport is wider than 768px.
- to lint the code before sending the PR with `npm run lint` or `yarn lint`

**Comment by d4rkener** [comment]
Gonna work on it

**Comment by rahuldahal-zz** [comment]
@rahulshawdev  sure!

**Comment by d4rkener** [comment]
The lines that you have suggested are not in the branch can you please guide me on which line from which file I need to change. OK now I understand you have two branches. Make development default branch for future contributors.

**Comment by rahuldahal-zz** [comment]
They are on the [development](https://github.com/askbuddie/askbuddie-bot-docs/blob/development/styles/custom.css) branch.

You have to 
- fork this repository
- download/clone it locally
- do your edit
- run `npm run lint` or `yarn lint` and make sure there are no errors
- then push those changes to remote
- create a PR

**Comment by d4rkener** [comment]
OK

**Comment by d4rkener** [comment]
Change you default branch then

**Comment by d4rkener** [comment]
After cloning the project I couldn't change my branch from main to development please help

**Comment by rahuldahal-zz** [comment]
Please join our [discord](https://discord.com/invite/askbuddie) server for discussion.

**Comment by d4rkener** [comment]
You can change you development to be default then the problem will be solved

**Comment by rahuldahal-zz** [comment]
This is how you can change the branch
`git checkout [branch name]` eg. `git checkout development`

Let's not discuss further on this topic here.
You can join our discord server for further discussions.
